# Generated by Django 4.1.3 on 2022-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubgroup',
            name='avatar',
            field=models.ImageField(default='/no-image.png', upload_to='avatars_group/', verbose_name='Аватар'),
        ),
    ]
