# Generated by Django 4.1.3 on 2022-12-09 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('director', '0002_clubgroup_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qty_lesson',
            field=models.IntegerField(blank=True, default=0, verbose_name='Кол-во занятий'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата/время')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма')),
                ('assignment', models.CharField(blank=True, max_length=150, verbose_name='Назначение')),
                ('is_personal', models.BooleanField(default=False, verbose_name='Личное')),
                ('yookassa_id', models.CharField(blank=True, max_length=150, verbose_name='ID Yookassa')),
                ('yookassa_status', models.CharField(blank=True, max_length=20, verbose_name='Статус Yookassa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
