# Generated by Django 4.1.3 on 2022-12-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_student_qty_lesson_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='director.club', verbose_name='Клуб'),
        ),
    ]
