# Generated by Django 4.1.3 on 2022-12-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0004_payment_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='no_active_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отключения'),
        ),
    ]
