# Generated by Django 4.1.3 on 2022-11-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('periodicity', models.CharField(choices=[('D', 'Ежедневно'), ('W', 'Еженедельно'), ('W', 'Ежемесячно'), ('W', 'Ежеквартально'), ('Y', 'Ежегодно')], max_length=1, verbose_name='Периодичность')),
            ],
            options={
                'verbose_name': 'Услуга(у)',
                'verbose_name_plural': 'Услуги',
                'ordering': ['id'],
            },
        ),
    ]
